# Generated by Django 5.1.6 on 2025-02-16 03:19

import backend.zettle.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZettleCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('card_type', models.CharField(choices=[('text', 'Text Card'), ('image', 'Image Card'), ('url', 'URL Card'), ('model', 'Model Reference Card'), ('topic', 'Topic Card')], default='text', max_length=20)),
                ('title', models.CharField(blank=True, max_length=1023)),
                ('votes', models.IntegerField(default=1)),
                ('text', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, max_length=1023, null=True, upload_to=backend.zettle.models.get_image_upload_path)),
                ('document', models.FileField(blank=True, max_length=1023, null=True, upload_to=backend.zettle.models.get_file_upload_path)),
                ('url', models.URLField(blank=True, max_length=1023)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('x', models.IntegerField(blank=True, null=True)),
                ('y', models.IntegerField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('next', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev', to='zettle.zettlecard')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='zettle.zettlecard')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='zettle.zettlecard')),
                ('tags', models.ManyToManyField(blank=True, to='zettle.zettlecard')),
            ],
            options={
                'indexes': [models.Index(fields=['card_type'], name='zettle_zett_card_ty_94e314_idx'), models.Index(fields=['slug'], name='zettle_zett_slug_44d300_idx'), models.Index(fields=['content_type', 'object_id'], name='zettle_zett_content_8e414e_idx')],
            },
        ),
    ]
